In [3]:
import pandas as pd
http_request_df = pd.read_csv("processed_urls.csv")

In [4]:
from pycaret.classification import *
from sklearn.model_selection import train_test_split

In [5]:
train_set, test_set = train_test_split(http_request_df.loc[:8000,:])

In [6]:
clu1 = setup(data = train_set, target='type', \
             numeric_features=['unicode', 'inequality', 'pipe', 'semicolon', 'curlybrace', 'caret', 'consecutive_num', 'hyphen', 'underscore'])

In [7]:
best_model = compare_models()

In [8]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [9]:
results = predict_model(best_model, test_set)

In [21]:
test_set

,Unnamed: 0,url,type,unicode,inequality,pipe,semicolon,curlybrace,caret,consecutive_num,hyphen,underscore
311,311,en.wikipedia.org/wiki/Category:American_religi...,benign,0,0,0,0,0,0,0,0,2
4041,4041,okcareertech.org/foundation/hall%20of%20fame/d...,benign,0,0,0,0,0,0,2,0,0
2266,2266,lowercolumbia.edu/community/art-and-entertainm...,benign,0,0,0,0,0,0,0,3,0
3630,3630,theroot.com/buzz/chauncey-bailey-case-life-arr...,benign,0,0,0,0,0,0,0,6,0
3306,3306,http://9779.info/%E8%B1%86%E5%AD%90%E7%B2%98%E...,malware,0,0,0,0,0,0,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1743,1743,http://centrofierachiuduno.com/index.php?view=...,defacement,0,0,0,0,0,0,2,0,1
1720,1720,findcontractor.org/welding-state/IN-welding.htm,benign,0,0,0,0,0,0,0,2,0
7991,7991,http://www.designinsideonline.com.au/resources...,defacement,0,0,0,0,0,0,0,7,0
5821,5821,dog.halfbirthdayproducts.com,malware,0,0,0,0,0,0,0,0,0
4699,4699,answers.com/topic/titanic-1,benign,0,0,0,0,0,0,1,1,0

In [10]:
correct_pred_count = 0
for index in range(len(results['Label'])):
    if results['Label'].iloc[index] == results['type'].iloc[index]:
        correct_pred_count += 1

print(correct_pred_count / len(results['Label'])) # About 79.56% prediction accuracy using a random forest classifer

0.7956021989005497

In [11]:
save_model(best_model, 'basic_RF_url_classifier')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=['unicode',
                                                           'inequality', 'pipe',
                                                           'semicolon',
                                                           'curlybrace', 'caret',
                                                           'consecutive_num',
                                                           'hyphen',
                                                           'underscore'],
                                       target='type', time_features=[])),
                 ('imputer',
                  Simple_Imputer(cate...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='auto',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_impurity_split=None,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         n_estimators=100, n_jobs=-1,
                                         oob_score=False, random_state=7483,
                                         verbose=0, warm_start=False)]],
          verbose=False),
 'basic_RF_url_classifier.pkl')

In [12]:
loaded_model = load_model('basic_RF_url_classifier')

Transformation Pipeline and Model Successfully Loaded

In [13]:
type(loaded_model)

sklearn.pipeline.Pipeline