In [1]:
import pandas as pd
http_request_df = pd.read_csv("processed_urls.csv")

In [2]:
from pycaret.classification import *

In [3]:
clu1 = setup(data = http_request_df.loc[:4000,:], target='type', \
             numeric_features=['unicode', 'inequality', 'pipe', 'semicolon', 'curlybrace', 'caret'])

In [4]:
best_models = compare_models()

In [5]:
evaluate_model(best_models)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [6]:
predict_model(best_models, http_request_df.loc[0:4000,:])

,Unnamed: 0,url,type,unicode,inequality,pipe,semicolon,curlybrace,caret,Label
0,0,br-icloud.com.br,phishing,0,0,0,0,0,0,phishing
1,1,mp3raid.com/music/krizz_kaliko.html,benign,0,0,0,0,0,0,benign
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,0,0,0,0,0,0,benign
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,0,0,0,0,0,0,defacement
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,0,0,0,0,0,0,benign
...,...,...,...,...,...,...,...,...,...,...
3996,3996,yatedo.com/s/Holy+Family+Church+%28Kansas+City...,benign,0,0,0,0,0,0,benign
3997,3997,tntvideo.com/,benign,0,0,0,0,0,0,benign
3998,3998,http://fortune.com/video/2014/11/18/snapchat-r...,benign,0,0,0,0,0,0,benign
3999,3999,nxtbook.com/nxtbooks/sb/rts0110_tbg/index.php?...,benign,0,0,0,0,0,0,benign
4000,4000,http://www.gonzalespd.org/index.php?option=com...,defacement,0,0,0,0,0,0,benign

In [7]:
save_model(best_models, 'basic_svm_url_classifier')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=['Unnamed: 0'],
                                       ml_usecase='classification',
                                       numerical_features=['unicode',
                                                           'inequality', 'pipe',
                                                           'semicolon',
                                                           'curlybrace',
                                                           'caret'],
                                       target='type', time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_availab...
                  SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                                early_stopping=False, epsilon=0.1, eta0=0.001,
                                fit_intercept=True, l1_ratio=0.15,
                                learning_rate='optimal', loss='hinge',
                                max_iter=1000, n_iter_no_change=5, n_jobs=-1,
                                penalty='l2', power_t=0.5, random_state=8122,
                                shuffle=True, tol=0.001, validation_fraction=0.1,
                                verbose=0, warm_start=False)]],
          verbose=False),
 'basic_svm_url_classifier.pkl')